/********************************************************************************
** Form generated from reading UI file 'simuladorwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.13.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SIMULADORWINDOW_H
#define UI_SIMULADORWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_SimuladorWindow
{
public:
    QAction *actionMesero_1;
    QAction *actionMesero_2;
    QAction *actionMesero_3;
    QAction *actionMesero_4;
    QAction *actionMesero_5;
    QAction *actionMesero_6;
    QAction *actionMesero_7;
    QAction *actionMesero_8;
    QAction *actionMesero_9;
    QAction *actionMesero_10;
    QAction *actionMesero_11;
    QAction *actionMesero_12;
    QAction *actionMesero_13;
    QAction *actionMesero_14;
    QAction *actionMesero_15;
    QAction *actionMesero_16;
    QAction *actionMesero_17;
    QAction *actionMesero_18;
    QAction *actionMesero_19;
    QAction *actionMesero_20;
    QWidget *centralwidget;
    QTextEdit *QueueTextField;
    QLabel *QueueLabel;
    QLabel *QueueSizeLabel;
    QPushButton *ButtonClientGenerator;
    QTextEdit *ClientAssignerTextFiel;
    QPushButton *AssignTablesButton;
    QLabel *AssignerLabel;
    QTextEdit *TableInfoTextFiedl;
    QLabel *TableLabel;
    QLabel *TableIDLabel;
    QPushButton *Table16Button;
    QPushButton *Table17Button;
    QPushButton *Table18Button;
    QPushButton *Table19Button;
    QPushButton *Table20Button;
    QPushButton *Table11Button;
    QPushButton *Table15Button;
    QPushButton *Table12Button;
    QPushButton *Table13Button;
    QPushButton *Table14Button;
    QPushButton *Table2Button;
    QPushButton *Table6Button;
    QPushButton *Table10Button;
    QPushButton *Table7Button;
    QPushButton *Table8Button;
    QPushButton *Table4Button;
    QPushButton *Table5Button;
    QPushButton *Table3Button;
    QPushButton *Table9Button;
    QPushButton *Table1Button;
    QLabel *chefLabel1;
    QLabel *chefLabel1_2;
    QLabel *chefLabel1_3;
    QLabel *ChefDessertLabel;
    QLabel *ChefMealLabel;
    QLabel *ChefEntranceLabel;
    QPushButton *CookDessertButton;
    QPushButton *CookMealButton1;
    QPushButton *CookMealButton2;
    QPushButton *CookMealButton3;
    QPushButton *CookEntranceButton;
    QTextEdit *ChefTextField;
    QLabel *ChefTextLabel;
    QMenuBar *menubar;
    QMenu *menuMeseros;
    QMenu *menuTiempos;
    QMenu *menuReset;
    QMenu *menuMenu;
    QMenu *menuReservas;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *SimuladorWindow)
    {
        if (SimuladorWindow->objectName().isEmpty())
            SimuladorWindow->setObjectName(QString::fromUtf8("SimuladorWindow"));
        SimuladorWindow->resize(1913, 1106);
        QFont font;
        font.setFamily(QString::fromUtf8("Arial"));
        font.setBold(true);
        font.setItalic(true);
        font.setWeight(75);
        SimuladorWindow->setFont(font);
        actionMesero_1 = new QAction(SimuladorWindow);
        actionMesero_1->setObjectName(QString::fromUtf8("actionMesero_1"));
        actionMesero_1->setEnabled(false);
        actionMesero_1->setVisible(false);
        actionMesero_2 = new QAction(SimuladorWindow);
        actionMesero_2->setObjectName(QString::fromUtf8("actionMesero_2"));
        actionMesero_2->setVisible(false);
        actionMesero_3 = new QAction(SimuladorWindow);
        actionMesero_3->setObjectName(QString::fromUtf8("actionMesero_3"));
        actionMesero_3->setVisible(false);
        actionMesero_4 = new QAction(SimuladorWindow);
        actionMesero_4->setObjectName(QString::fromUtf8("actionMesero_4"));
        actionMesero_4->setVisible(false);
        actionMesero_5 = new QAction(SimuladorWindow);
        actionMesero_5->setObjectName(QString::fromUtf8("actionMesero_5"));
        actionMesero_5->setVisible(false);
        actionMesero_6 = new QAction(SimuladorWindow);
        actionMesero_6->setObjectName(QString::fromUtf8("actionMesero_6"));
        actionMesero_6->setVisible(false);
        actionMesero_7 = new QAction(SimuladorWindow);
        actionMesero_7->setObjectName(QString::fromUtf8("actionMesero_7"));
        actionMesero_7->setVisible(false);
        actionMesero_8 = new QAction(SimuladorWindow);
        actionMesero_8->setObjectName(QString::fromUtf8("actionMesero_8"));
        actionMesero_8->setVisible(false);
        actionMesero_9 = new QAction(SimuladorWindow);
        actionMesero_9->setObjectName(QString::fromUtf8("actionMesero_9"));
        actionMesero_9->setVisible(false);
        actionMesero_10 = new QAction(SimuladorWindow);
        actionMesero_10->setObjectName(QString::fromUtf8("actionMesero_10"));
        actionMesero_10->setVisible(false);
        actionMesero_11 = new QAction(SimuladorWindow);
        actionMesero_11->setObjectName(QString::fromUtf8("actionMesero_11"));
        actionMesero_11->setVisible(false);
        actionMesero_12 = new QAction(SimuladorWindow);
        actionMesero_12->setObjectName(QString::fromUtf8("actionMesero_12"));
        actionMesero_12->setVisible(false);
        actionMesero_13 = new QAction(SimuladorWindow);
        actionMesero_13->setObjectName(QString::fromUtf8("actionMesero_13"));
        actionMesero_13->setVisible(false);
        actionMesero_14 = new QAction(SimuladorWindow);
        actionMesero_14->setObjectName(QString::fromUtf8("actionMesero_14"));
        actionMesero_14->setVisible(false);
        actionMesero_15 = new QAction(SimuladorWindow);
        actionMesero_15->setObjectName(QString::fromUtf8("actionMesero_15"));
        actionMesero_15->setVisible(false);
        actionMesero_16 = new QAction(SimuladorWindow);
        actionMesero_16->setObjectName(QString::fromUtf8("actionMesero_16"));
        actionMesero_16->setVisible(false);
        actionMesero_17 = new QAction(SimuladorWindow);
        actionMesero_17->setObjectName(QString::fromUtf8("actionMesero_17"));
        actionMesero_17->setVisible(false);
        actionMesero_18 = new QAction(SimuladorWindow);
        actionMesero_18->setObjectName(QString::fromUtf8("actionMesero_18"));
        actionMesero_18->setVisible(false);
        actionMesero_19 = new QAction(SimuladorWindow);
        actionMesero_19->setObjectName(QString::fromUtf8("actionMesero_19"));
        actionMesero_19->setVisible(false);
        actionMesero_20 = new QAction(SimuladorWindow);
        actionMesero_20->setObjectName(QString::fromUtf8("actionMesero_20"));
        actionMesero_20->setVisible(false);
        centralwidget = new QWidget(SimuladorWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        QueueTextField = new QTextEdit(centralwidget);
        QueueTextField->setObjectName(QString::fromUtf8("QueueTextField"));
        QueueTextField->setEnabled(true);
        QueueTextField->setGeometry(QRect(1520, 755, 381, 191));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Arial Black"));
        font1.setBold(true);
        font1.setItalic(false);
        font1.setWeight(75);
        QueueTextField->setFont(font1);
        QueueTextField->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        QueueTextField->setReadOnly(true);
        QueueLabel = new QLabel(centralwidget);
        QueueLabel->setObjectName(QString::fromUtf8("QueueLabel"));
        QueueLabel->setGeometry(QRect(1540, 715, 161, 31));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Arial Black"));
        font2.setPointSize(10);
        font2.setBold(true);
        font2.setItalic(true);
        font2.setWeight(75);
        QueueLabel->setFont(font2);
        QueueSizeLabel = new QLabel(centralwidget);
        QueueSizeLabel->setObjectName(QString::fromUtf8("QueueSizeLabel"));
        QueueSizeLabel->setGeometry(QRect(1680, 705, 111, 51));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Arial Black"));
        font3.setPointSize(10);
        font3.setBold(true);
        font3.setItalic(false);
        font3.setWeight(75);
        QueueSizeLabel->setFont(font3);
        ButtonClientGenerator = new QPushButton(centralwidget);
        ButtonClientGenerator->setObjectName(QString::fromUtf8("ButtonClientGenerator"));
        ButtonClientGenerator->setGeometry(QRect(1730, 715, 151, 31));
        QFont font4;
        font4.setFamily(QString::fromUtf8("Arial"));
        font4.setPointSize(10);
        font4.setBold(true);
        font4.setItalic(false);
        font4.setWeight(75);
        ButtonClientGenerator->setFont(font4);
        ClientAssignerTextFiel = new QTextEdit(centralwidget);
        ClientAssignerTextFiel->setObjectName(QString::fromUtf8("ClientAssignerTextFiel"));
        ClientAssignerTextFiel->setEnabled(true);
        ClientAssignerTextFiel->setGeometry(QRect(1520, 515, 381, 171));
        ClientAssignerTextFiel->setFont(font1);
        ClientAssignerTextFiel->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        ClientAssignerTextFiel->setReadOnly(true);
        AssignTablesButton = new QPushButton(centralwidget);
        AssignTablesButton->setObjectName(QString::fromUtf8("AssignTablesButton"));
        AssignTablesButton->setGeometry(QRect(1740, 469, 161, 31));
        AssignTablesButton->setFont(font4);
        AssignerLabel = new QLabel(centralwidget);
        AssignerLabel->setObjectName(QString::fromUtf8("AssignerLabel"));
        AssignerLabel->setGeometry(QRect(1540, 480, 151, 21));
        QFont font5;
        font5.setFamily(QString::fromUtf8("Arial Black"));
        font5.setPointSize(10);
        font5.setItalic(false);
        AssignerLabel->setFont(font5);
        TableInfoTextFiedl = new QTextEdit(centralwidget);
        TableInfoTextFiedl->setObjectName(QString::fromUtf8("TableInfoTextFiedl"));
        TableInfoTextFiedl->setGeometry(QRect(1523, 264, 381, 171));
        QFont font6;
        font6.setFamily(QString::fromUtf8("Arial Black"));
        font6.setPointSize(8);
        font6.setItalic(false);
        TableInfoTextFiedl->setFont(font6);
        TableInfoTextFiedl->setReadOnly(true);
        TableLabel = new QLabel(centralwidget);
        TableLabel->setObjectName(QString::fromUtf8("TableLabel"));
        TableLabel->setGeometry(QRect(1540, 220, 131, 51));
        TableLabel->setFont(font5);
        TableIDLabel = new QLabel(centralwidget);
        TableIDLabel->setObjectName(QString::fromUtf8("TableIDLabel"));
        TableIDLabel->setGeometry(QRect(1620, 230, 71, 31));
        TableIDLabel->setFont(font5);
        Table16Button = new QPushButton(centralwidget);
        Table16Button->setObjectName(QString::fromUtf8("Table16Button"));
        Table16Button->setGeometry(QRect(150, 870, 80, 25));
        QFont font7;
        font7.setFamily(QString::fromUtf8("Arial"));
        font7.setPointSize(10);
        font7.setBold(false);
        font7.setItalic(true);
        font7.setWeight(50);
        Table16Button->setFont(font7);
        Table17Button = new QPushButton(centralwidget);
        Table17Button->setObjectName(QString::fromUtf8("Table17Button"));
        Table17Button->setGeometry(QRect(350, 870, 80, 25));
        Table17Button->setFont(font7);
        Table18Button = new QPushButton(centralwidget);
        Table18Button->setObjectName(QString::fromUtf8("Table18Button"));
        Table18Button->setGeometry(QRect(550, 870, 80, 25));
        Table18Button->setFont(font7);
        Table19Button = new QPushButton(centralwidget);
        Table19Button->setObjectName(QString::fromUtf8("Table19Button"));
        Table19Button->setGeometry(QRect(750, 870, 80, 25));
        Table19Button->setFont(font7);
        Table20Button = new QPushButton(centralwidget);
        Table20Button->setObjectName(QString::fromUtf8("Table20Button"));
        Table20Button->setGeometry(QRect(950, 870, 80, 25));
        Table20Button->setFont(font7);
        Table11Button = new QPushButton(centralwidget);
        Table11Button->setObjectName(QString::fromUtf8("Table11Button"));
        Table11Button->setGeometry(QRect(150, 670, 80, 25));
        Table11Button->setFont(font7);
        Table15Button = new QPushButton(centralwidget);
        Table15Button->setObjectName(QString::fromUtf8("Table15Button"));
        Table15Button->setGeometry(QRect(950, 670, 80, 25));
        Table15Button->setFont(font7);
        Table12Button = new QPushButton(centralwidget);
        Table12Button->setObjectName(QString::fromUtf8("Table12Button"));
        Table12Button->setGeometry(QRect(350, 670, 80, 25));
        Table12Button->setFont(font7);
        Table13Button = new QPushButton(centralwidget);
        Table13Button->setObjectName(QString::fromUtf8("Table13Button"));
        Table13Button->setGeometry(QRect(550, 670, 80, 25));
        Table13Button->setFont(font7);
        Table14Button = new QPushButton(centralwidget);
        Table14Button->setObjectName(QString::fromUtf8("Table14Button"));
        Table14Button->setGeometry(QRect(750, 670, 80, 25));
        Table14Button->setFont(font7);
        Table2Button = new QPushButton(centralwidget);
        Table2Button->setObjectName(QString::fromUtf8("Table2Button"));
        Table2Button->setGeometry(QRect(350, 270, 80, 25));
        Table2Button->setFont(font7);
        Table6Button = new QPushButton(centralwidget);
        Table6Button->setObjectName(QString::fromUtf8("Table6Button"));
        Table6Button->setGeometry(QRect(150, 470, 80, 25));
        Table6Button->setFont(font7);
        Table10Button = new QPushButton(centralwidget);
        Table10Button->setObjectName(QString::fromUtf8("Table10Button"));
        Table10Button->setGeometry(QRect(950, 470, 80, 25));
        Table10Button->setFont(font7);
        Table7Button = new QPushButton(centralwidget);
        Table7Button->setObjectName(QString::fromUtf8("Table7Button"));
        Table7Button->setGeometry(QRect(350, 470, 80, 25));
        Table7Button->setFont(font7);
        Table8Button = new QPushButton(centralwidget);
        Table8Button->setObjectName(QString::fromUtf8("Table8Button"));
        Table8Button->setGeometry(QRect(550, 470, 80, 25));
        Table8Button->setFont(font7);
        Table4Button = new QPushButton(centralwidget);
        Table4Button->setObjectName(QString::fromUtf8("Table4Button"));
        Table4Button->setGeometry(QRect(750, 270, 80, 25));
        Table4Button->setFont(font7);
        Table5Button = new QPushButton(centralwidget);
        Table5Button->setObjectName(QString::fromUtf8("Table5Button"));
        Table5Button->setGeometry(QRect(950, 270, 80, 25));
        Table5Button->setFont(font7);
        Table3Button = new QPushButton(centralwidget);
        Table3Button->setObjectName(QString::fromUtf8("Table3Button"));
        Table3Button->setGeometry(QRect(550, 270, 80, 25));
        Table3Button->setFont(font7);
        Table9Button = new QPushButton(centralwidget);
        Table9Button->setObjectName(QString::fromUtf8("Table9Button"));
        Table9Button->setGeometry(QRect(750, 470, 80, 25));
        Table9Button->setFont(font7);
        Table1Button = new QPushButton(centralwidget);
        Table1Button->setObjectName(QString::fromUtf8("Table1Button"));
        Table1Button->setGeometry(QRect(150, 270, 80, 25));
        Table1Button->setFont(font7);
        chefLabel1 = new QLabel(centralwidget);
        chefLabel1->setObjectName(QString::fromUtf8("chefLabel1"));
        chefLabel1->setGeometry(QRect(1280, 750, 201, 201));
        chefLabel1_2 = new QLabel(centralwidget);
        chefLabel1_2->setObjectName(QString::fromUtf8("chefLabel1_2"));
        chefLabel1_2->setGeometry(QRect(1290, 180, 171, 231));
        chefLabel1_3 = new QLabel(centralwidget);
        chefLabel1_3->setObjectName(QString::fromUtf8("chefLabel1_3"));
        chefLabel1_3->setGeometry(QRect(1280, 470, 171, 241));
        ChefDessertLabel = new QLabel(centralwidget);
        ChefDessertLabel->setObjectName(QString::fromUtf8("ChefDessertLabel"));
        ChefDessertLabel->setGeometry(QRect(1270, 715, 141, 21));
        ChefDessertLabel->setFont(font5);
        ChefMealLabel = new QLabel(centralwidget);
        ChefMealLabel->setObjectName(QString::fromUtf8("ChefMealLabel"));
        ChefMealLabel->setGeometry(QRect(1270, 440, 201, 21));
        ChefMealLabel->setFont(font5);
        ChefEntranceLabel = new QLabel(centralwidget);
        ChefEntranceLabel->setObjectName(QString::fromUtf8("ChefEntranceLabel"));
        ChefEntranceLabel->setGeometry(QRect(1280, 150, 201, 21));
        ChefEntranceLabel->setFont(font5);
        CookDessertButton = new QPushButton(centralwidget);
        CookDessertButton->setObjectName(QString::fromUtf8("CookDessertButton"));
        CookDessertButton->setGeometry(QRect(1140, 830, 111, 41));
        QFont font8;
        font8.setPointSize(10);
        CookDessertButton->setFont(font8);
        CookMealButton1 = new QPushButton(centralwidget);
        CookMealButton1->setObjectName(QString::fromUtf8("CookMealButton1"));
        CookMealButton1->setGeometry(QRect(1140, 620, 111, 41));
        CookMealButton1->setFont(font8);
        CookMealButton2 = new QPushButton(centralwidget);
        CookMealButton2->setObjectName(QString::fromUtf8("CookMealButton2"));
        CookMealButton2->setGeometry(QRect(1140, 570, 111, 41));
        CookMealButton2->setFont(font8);
        CookMealButton3 = new QPushButton(centralwidget);
        CookMealButton3->setObjectName(QString::fromUtf8("CookMealButton3"));
        CookMealButton3->setGeometry(QRect(1140, 520, 111, 41));
        CookMealButton3->setFont(font8);
        CookEntranceButton = new QPushButton(centralwidget);
        CookEntranceButton->setObjectName(QString::fromUtf8("CookEntranceButton"));
        CookEntranceButton->setGeometry(QRect(1140, 260, 111, 41));
        CookEntranceButton->setFont(font8);
        ChefTextField = new QTextEdit(centralwidget);
        ChefTextField->setObjectName(QString::fromUtf8("ChefTextField"));
        ChefTextField->setGeometry(QRect(1523, 70, 381, 141));
        QFont font9;
        font9.setFamily(QString::fromUtf8("Arial Black"));
        font9.setItalic(false);
        ChefTextField->setFont(font9);
        ChefTextField->setReadOnly(true);
        ChefTextLabel = new QLabel(centralwidget);
        ChefTextLabel->setObjectName(QString::fromUtf8("ChefTextLabel"));
        ChefTextLabel->setGeometry(QRect(1540, 30, 91, 31));
        ChefTextLabel->setFont(font5);
        SimuladorWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(SimuladorWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1913, 25));
        menuMeseros = new QMenu(menubar);
        menuMeseros->setObjectName(QString::fromUtf8("menuMeseros"));
        menuTiempos = new QMenu(menubar);
        menuTiempos->setObjectName(QString::fromUtf8("menuTiempos"));
        menuReset = new QMenu(menubar);
        menuReset->setObjectName(QString::fromUtf8("menuReset"));
        menuMenu = new QMenu(menubar);
        menuMenu->setObjectName(QString::fromUtf8("menuMenu"));
        menuReservas = new QMenu(menubar);
        menuReservas->setObjectName(QString::fromUtf8("menuReservas"));
        SimuladorWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(SimuladorWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        SimuladorWindow->setStatusBar(statusbar);

        menubar->addAction(menuMeseros->menuAction());
        menubar->addAction(menuTiempos->menuAction());
        menubar->addAction(menuReset->menuAction());
        menubar->addAction(menuMenu->menuAction());
        menubar->addAction(menuReservas->menuAction());
        menuMeseros->addSeparator();
        menuMeseros->addAction(actionMesero_1);
        menuMeseros->addAction(actionMesero_2);
        menuMeseros->addAction(actionMesero_3);
        menuMeseros->addAction(actionMesero_4);
        menuMeseros->addAction(actionMesero_5);
        menuMeseros->addAction(actionMesero_6);
        menuMeseros->addAction(actionMesero_7);
        menuMeseros->addAction(actionMesero_8);
        menuMeseros->addAction(actionMesero_9);
        menuMeseros->addAction(actionMesero_10);
        menuMeseros->addAction(actionMesero_11);
        menuMeseros->addAction(actionMesero_12);
        menuMeseros->addAction(actionMesero_13);
        menuMeseros->addAction(actionMesero_14);
        menuMeseros->addAction(actionMesero_15);
        menuMeseros->addAction(actionMesero_16);
        menuMeseros->addAction(actionMesero_17);
        menuMeseros->addAction(actionMesero_18);
        menuMeseros->addAction(actionMesero_19);
        menuMeseros->addAction(actionMesero_20);

        retranslateUi(SimuladorWindow);

        QMetaObject::connectSlotsByName(SimuladorWindow);
    } // setupUi

    void retranslateUi(QMainWindow *SimuladorWindow)
    {
        SimuladorWindow->setWindowTitle(QCoreApplication::translate("SimuladorWindow", "SimuladorWindow", nullptr));
        actionMesero_1->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 1", nullptr));
        actionMesero_2->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 2", nullptr));
        actionMesero_3->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 3", nullptr));
        actionMesero_4->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 4", nullptr));
        actionMesero_5->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 5", nullptr));
        actionMesero_6->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 6", nullptr));
        actionMesero_7->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 7 ", nullptr));
        actionMesero_8->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 8", nullptr));
        actionMesero_9->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 9", nullptr));
        actionMesero_10->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 10", nullptr));
        actionMesero_11->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 11", nullptr));
        actionMesero_12->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 12", nullptr));
        actionMesero_13->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 13", nullptr));
        actionMesero_14->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 14", nullptr));
        actionMesero_15->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 15", nullptr));
        actionMesero_16->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 16", nullptr));
        actionMesero_17->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 17", nullptr));
        actionMesero_18->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 18", nullptr));
        actionMesero_19->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 19", nullptr));
        actionMesero_20->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 20", nullptr));
        QueueLabel->setText(QCoreApplication::translate("SimuladorWindow", "Gente en cola: ", nullptr));
        QueueSizeLabel->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        ButtonClientGenerator->setText(QCoreApplication::translate("SimuladorWindow", "Generar Clientes", nullptr));
        AssignTablesButton->setText(QCoreApplication::translate("SimuladorWindow", "Asignar Cientes", nullptr));
        AssignerLabel->setText(QCoreApplication::translate("SimuladorWindow", "Recepcionista", nullptr));
        TableLabel->setText(QCoreApplication::translate("SimuladorWindow", "Mesa #", nullptr));
        TableIDLabel->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        Table16Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table17Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table18Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table19Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table20Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table11Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table15Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table12Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table13Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table14Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table2Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table6Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table10Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table7Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table8Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table4Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table5Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table3Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table9Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table1Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        chefLabel1->setText(QString());
        chefLabel1_2->setText(QString());
        chefLabel1_3->setText(QString());
        ChefDessertLabel->setText(QCoreApplication::translate("SimuladorWindow", "Chef Postres", nullptr));
        ChefMealLabel->setText(QCoreApplication::translate("SimuladorWindow", "Chefs Platos Fuertes", nullptr));
        ChefEntranceLabel->setText(QCoreApplication::translate("SimuladorWindow", "Chef Entradas", nullptr));
        CookDessertButton->setText(QCoreApplication::translate("SimuladorWindow", "Cocinar", nullptr));
        CookMealButton1->setText(QCoreApplication::translate("SimuladorWindow", "Cocinar", nullptr));
        CookMealButton2->setText(QCoreApplication::translate("SimuladorWindow", "Cocinar", nullptr));
        CookMealButton3->setText(QCoreApplication::translate("SimuladorWindow", "Cocinar", nullptr));
        CookEntranceButton->setText(QCoreApplication::translate("SimuladorWindow", "Cocinar", nullptr));
        ChefTextLabel->setText(QCoreApplication::translate("SimuladorWindow", "Chefs:", nullptr));
        menuMeseros->setTitle(QCoreApplication::translate("SimuladorWindow", "Meseros", nullptr));
        menuTiempos->setTitle(QCoreApplication::translate("SimuladorWindow", "Tiempos", nullptr));
        menuReset->setTitle(QCoreApplication::translate("SimuladorWindow", "Reset", nullptr));
        menuMenu->setTitle(QCoreApplication::translate("SimuladorWindow", "Menu", nullptr));
        menuReservas->setTitle(QCoreApplication::translate("SimuladorWindow", "Reservas", nullptr));
    } // retranslateUi

};

namespace Ui {
    class SimuladorWindow: public Ui_SimuladorWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SIMULADORWINDOW_H
