/********************************************************************************
** Form generated from reading UI file 'simuladorwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.13.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SIMULADORWINDOW_H
#define UI_SIMULADORWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_SimuladorWindow
{
public:
    QAction *actionMesero_1;
    QAction *actionMesero_2;
    QAction *actionMesero_3;
    QAction *actionMesero_4;
    QAction *actionMesero_5;
    QAction *actionMesero_6;
    QAction *actionMesero_7;
    QAction *actionMesero_8;
    QAction *actionMesero_9;
    QAction *actionMesero_10;
    QAction *actionMesero_11;
    QAction *actionMesero_12;
    QAction *actionMesero_13;
    QAction *actionMesero_14;
    QAction *actionMesero_15;
    QAction *actionMesero_16;
    QAction *actionMesero_17;
    QAction *actionMesero_18;
    QAction *actionMesero_19;
    QAction *actionMesero_20;
    QAction *actionIntervalo_de_llegada;
    QAction *actionProbabilidad_de_plato_fuerte;
    QAction *actionRestart_Simulation;
    QAction *actionVer_Menu;
    QAction *actionSolicitar_Reserva;
    QAction *actionStart;
    QAction *actionDetener;
    QWidget *centralwidget;
    QTextEdit *QueueTextField;
    QLabel *QueueLabel;
    QLabel *QueueSizeLabel;
    QPushButton *ButtonClientGenerator;
    QTextEdit *ClientAssignerTextFiel;
    QPushButton *AssignTablesButton;
    QLabel *AssignerLabel;
    QTextEdit *TableInfoTextFiedl;
    QLabel *TableLabel;
    QLabel *TableIDLabel;
    QPushButton *Table16Button;
    QPushButton *Table17Button;
    QPushButton *Table18Button;
    QPushButton *Table19Button;
    QPushButton *Table20Button;
    QPushButton *Table11Button;
    QPushButton *Table15Button;
    QPushButton *Table12Button;
    QPushButton *Table13Button;
    QPushButton *Table14Button;
    QPushButton *Table2Button;
    QPushButton *Table6Button;
    QPushButton *Table10Button;
    QPushButton *Table7Button;
    QPushButton *Table8Button;
    QPushButton *Table4Button;
    QPushButton *Table5Button;
    QPushButton *Table3Button;
    QPushButton *Table9Button;
    QPushButton *Table1Button;
    QLabel *chefLabel1;
    QLabel *chefLabel1_2;
    QLabel *chefLabel1_3;
    QLabel *ChefDessertLabel;
    QLabel *ChefMealLabel;
    QLabel *ChefEntranceLabel;
    QPushButton *CookDessertButton;
    QPushButton *CookMealButton1;
    QPushButton *CookMealButton2;
    QPushButton *CookMealButton3;
    QPushButton *CookEntranceButton;
    QTextEdit *ChefTextField;
    QLabel *ChefTextLabel;
    QLabel *TableTime1;
    QLabel *TableTime2;
    QLabel *TableTime3;
    QLabel *TableTime4;
    QLabel *TableTime5;
    QLabel *TableTime7;
    QLabel *TableTime9;
    QLabel *TableTime8;
    QLabel *TableTime10;
    QLabel *TableTime6;
    QLabel *TableTime12;
    QLabel *TableTime14;
    QLabel *TableTime13;
    QLabel *TableTime15;
    QLabel *TableTime11;
    QLabel *TableTime17;
    QLabel *TableTime19;
    QLabel *TableTime18;
    QLabel *TableTime20;
    QLabel *TableTime16;
    QTextEdit *CashTextField;
    QTextEdit *WashTextField;
    QPushButton *CashPauseButton;
    QPushButton *TypeCashButton;
    QLabel *CashierLabel;
    QLabel *CashierLabel_2;
    QLabel *label;
    QLabel *cantDePlatos;
    QMenuBar *menubar;
    QMenu *menuMeseros;
    QMenu *menuTiempos;
    QMenu *menuReset;
    QMenu *menuMenu;
    QMenu *menuReservas;
    QMenu *menuSimulacion;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *SimuladorWindow)
    {
        if (SimuladorWindow->objectName().isEmpty())
            SimuladorWindow->setObjectName(QString::fromUtf8("SimuladorWindow"));
        SimuladorWindow->resize(1913, 1106);
        QFont font;
        font.setFamily(QString::fromUtf8("Arial"));
        font.setBold(true);
        font.setItalic(true);
        font.setWeight(75);
        SimuladorWindow->setFont(font);
        actionMesero_1 = new QAction(SimuladorWindow);
        actionMesero_1->setObjectName(QString::fromUtf8("actionMesero_1"));
        actionMesero_1->setEnabled(false);
        actionMesero_1->setVisible(false);
        actionMesero_2 = new QAction(SimuladorWindow);
        actionMesero_2->setObjectName(QString::fromUtf8("actionMesero_2"));
        actionMesero_2->setVisible(false);
        actionMesero_3 = new QAction(SimuladorWindow);
        actionMesero_3->setObjectName(QString::fromUtf8("actionMesero_3"));
        actionMesero_3->setVisible(false);
        actionMesero_4 = new QAction(SimuladorWindow);
        actionMesero_4->setObjectName(QString::fromUtf8("actionMesero_4"));
        actionMesero_4->setVisible(false);
        actionMesero_5 = new QAction(SimuladorWindow);
        actionMesero_5->setObjectName(QString::fromUtf8("actionMesero_5"));
        actionMesero_5->setVisible(false);
        actionMesero_6 = new QAction(SimuladorWindow);
        actionMesero_6->setObjectName(QString::fromUtf8("actionMesero_6"));
        actionMesero_6->setVisible(false);
        actionMesero_7 = new QAction(SimuladorWindow);
        actionMesero_7->setObjectName(QString::fromUtf8("actionMesero_7"));
        actionMesero_7->setVisible(false);
        actionMesero_8 = new QAction(SimuladorWindow);
        actionMesero_8->setObjectName(QString::fromUtf8("actionMesero_8"));
        actionMesero_8->setVisible(false);
        actionMesero_9 = new QAction(SimuladorWindow);
        actionMesero_9->setObjectName(QString::fromUtf8("actionMesero_9"));
        actionMesero_9->setVisible(false);
        actionMesero_10 = new QAction(SimuladorWindow);
        actionMesero_10->setObjectName(QString::fromUtf8("actionMesero_10"));
        actionMesero_10->setVisible(false);
        actionMesero_11 = new QAction(SimuladorWindow);
        actionMesero_11->setObjectName(QString::fromUtf8("actionMesero_11"));
        actionMesero_11->setVisible(false);
        actionMesero_12 = new QAction(SimuladorWindow);
        actionMesero_12->setObjectName(QString::fromUtf8("actionMesero_12"));
        actionMesero_12->setVisible(false);
        actionMesero_13 = new QAction(SimuladorWindow);
        actionMesero_13->setObjectName(QString::fromUtf8("actionMesero_13"));
        actionMesero_13->setVisible(false);
        actionMesero_14 = new QAction(SimuladorWindow);
        actionMesero_14->setObjectName(QString::fromUtf8("actionMesero_14"));
        actionMesero_14->setVisible(false);
        actionMesero_15 = new QAction(SimuladorWindow);
        actionMesero_15->setObjectName(QString::fromUtf8("actionMesero_15"));
        actionMesero_15->setVisible(false);
        actionMesero_16 = new QAction(SimuladorWindow);
        actionMesero_16->setObjectName(QString::fromUtf8("actionMesero_16"));
        actionMesero_16->setVisible(false);
        actionMesero_17 = new QAction(SimuladorWindow);
        actionMesero_17->setObjectName(QString::fromUtf8("actionMesero_17"));
        actionMesero_17->setVisible(false);
        actionMesero_18 = new QAction(SimuladorWindow);
        actionMesero_18->setObjectName(QString::fromUtf8("actionMesero_18"));
        actionMesero_18->setVisible(false);
        actionMesero_19 = new QAction(SimuladorWindow);
        actionMesero_19->setObjectName(QString::fromUtf8("actionMesero_19"));
        actionMesero_19->setVisible(false);
        actionMesero_20 = new QAction(SimuladorWindow);
        actionMesero_20->setObjectName(QString::fromUtf8("actionMesero_20"));
        actionMesero_20->setVisible(false);
        actionIntervalo_de_llegada = new QAction(SimuladorWindow);
        actionIntervalo_de_llegada->setObjectName(QString::fromUtf8("actionIntervalo_de_llegada"));
        actionProbabilidad_de_plato_fuerte = new QAction(SimuladorWindow);
        actionProbabilidad_de_plato_fuerte->setObjectName(QString::fromUtf8("actionProbabilidad_de_plato_fuerte"));
        actionRestart_Simulation = new QAction(SimuladorWindow);
        actionRestart_Simulation->setObjectName(QString::fromUtf8("actionRestart_Simulation"));
        actionVer_Menu = new QAction(SimuladorWindow);
        actionVer_Menu->setObjectName(QString::fromUtf8("actionVer_Menu"));
        actionSolicitar_Reserva = new QAction(SimuladorWindow);
        actionSolicitar_Reserva->setObjectName(QString::fromUtf8("actionSolicitar_Reserva"));
        actionStart = new QAction(SimuladorWindow);
        actionStart->setObjectName(QString::fromUtf8("actionStart"));
        actionDetener = new QAction(SimuladorWindow);
        actionDetener->setObjectName(QString::fromUtf8("actionDetener"));
        centralwidget = new QWidget(SimuladorWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        QueueTextField = new QTextEdit(centralwidget);
        QueueTextField->setObjectName(QString::fromUtf8("QueueTextField"));
        QueueTextField->setEnabled(true);
        QueueTextField->setGeometry(QRect(1520, 755, 381, 191));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Monotype Corsiva"));
        font1.setPointSize(12);
        font1.setBold(false);
        font1.setItalic(true);
        font1.setWeight(50);
        QueueTextField->setFont(font1);
        QueueTextField->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        QueueTextField->setReadOnly(true);
        QueueLabel = new QLabel(centralwidget);
        QueueLabel->setObjectName(QString::fromUtf8("QueueLabel"));
        QueueLabel->setGeometry(QRect(1540, 715, 161, 31));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Monotype Corsiva"));
        font2.setPointSize(14);
        font2.setBold(false);
        font2.setItalic(true);
        font2.setWeight(50);
        QueueLabel->setFont(font2);
        QueueSizeLabel = new QLabel(centralwidget);
        QueueSizeLabel->setObjectName(QString::fromUtf8("QueueSizeLabel"));
        QueueSizeLabel->setGeometry(QRect(1680, 705, 111, 51));
        QueueSizeLabel->setFont(font2);
        ButtonClientGenerator = new QPushButton(centralwidget);
        ButtonClientGenerator->setObjectName(QString::fromUtf8("ButtonClientGenerator"));
        ButtonClientGenerator->setGeometry(QRect(1730, 715, 151, 31));
        ButtonClientGenerator->setFont(font2);
        ClientAssignerTextFiel = new QTextEdit(centralwidget);
        ClientAssignerTextFiel->setObjectName(QString::fromUtf8("ClientAssignerTextFiel"));
        ClientAssignerTextFiel->setEnabled(true);
        ClientAssignerTextFiel->setGeometry(QRect(1520, 515, 381, 171));
        ClientAssignerTextFiel->setFont(font1);
        ClientAssignerTextFiel->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        ClientAssignerTextFiel->setReadOnly(true);
        AssignTablesButton = new QPushButton(centralwidget);
        AssignTablesButton->setObjectName(QString::fromUtf8("AssignTablesButton"));
        AssignTablesButton->setGeometry(QRect(1740, 469, 161, 31));
        AssignTablesButton->setFont(font1);
        AssignerLabel = new QLabel(centralwidget);
        AssignerLabel->setObjectName(QString::fromUtf8("AssignerLabel"));
        AssignerLabel->setGeometry(QRect(1540, 480, 151, 21));
        AssignerLabel->setFont(font2);
        TableInfoTextFiedl = new QTextEdit(centralwidget);
        TableInfoTextFiedl->setObjectName(QString::fromUtf8("TableInfoTextFiedl"));
        TableInfoTextFiedl->setGeometry(QRect(1523, 264, 381, 171));
        TableInfoTextFiedl->setFont(font1);
        TableInfoTextFiedl->setReadOnly(true);
        TableLabel = new QLabel(centralwidget);
        TableLabel->setObjectName(QString::fromUtf8("TableLabel"));
        TableLabel->setGeometry(QRect(1540, 220, 131, 51));
        TableLabel->setFont(font2);
        TableIDLabel = new QLabel(centralwidget);
        TableIDLabel->setObjectName(QString::fromUtf8("TableIDLabel"));
        TableIDLabel->setGeometry(QRect(1620, 230, 71, 31));
        TableIDLabel->setFont(font2);
        Table16Button = new QPushButton(centralwidget);
        Table16Button->setObjectName(QString::fromUtf8("Table16Button"));
        Table16Button->setGeometry(QRect(150, 890, 80, 25));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Arial"));
        font3.setPointSize(10);
        font3.setBold(false);
        font3.setItalic(true);
        font3.setWeight(50);
        Table16Button->setFont(font3);
        Table17Button = new QPushButton(centralwidget);
        Table17Button->setObjectName(QString::fromUtf8("Table17Button"));
        Table17Button->setGeometry(QRect(350, 890, 80, 25));
        Table17Button->setFont(font3);
        Table18Button = new QPushButton(centralwidget);
        Table18Button->setObjectName(QString::fromUtf8("Table18Button"));
        Table18Button->setGeometry(QRect(550, 890, 80, 25));
        Table18Button->setFont(font3);
        Table19Button = new QPushButton(centralwidget);
        Table19Button->setObjectName(QString::fromUtf8("Table19Button"));
        Table19Button->setGeometry(QRect(750, 890, 80, 25));
        Table19Button->setFont(font3);
        Table20Button = new QPushButton(centralwidget);
        Table20Button->setObjectName(QString::fromUtf8("Table20Button"));
        Table20Button->setGeometry(QRect(950, 890, 80, 25));
        Table20Button->setFont(font3);
        Table11Button = new QPushButton(centralwidget);
        Table11Button->setObjectName(QString::fromUtf8("Table11Button"));
        Table11Button->setGeometry(QRect(150, 690, 80, 25));
        QFont font4;
        font4.setFamily(QString::fromUtf8("Monotype Corsiva"));
        font4.setPointSize(16);
        font4.setBold(false);
        font4.setItalic(true);
        font4.setWeight(50);
        Table11Button->setFont(font4);
        Table15Button = new QPushButton(centralwidget);
        Table15Button->setObjectName(QString::fromUtf8("Table15Button"));
        Table15Button->setGeometry(QRect(950, 690, 80, 25));
        Table15Button->setFont(font4);
        Table12Button = new QPushButton(centralwidget);
        Table12Button->setObjectName(QString::fromUtf8("Table12Button"));
        Table12Button->setGeometry(QRect(350, 690, 80, 25));
        Table12Button->setFont(font4);
        Table13Button = new QPushButton(centralwidget);
        Table13Button->setObjectName(QString::fromUtf8("Table13Button"));
        Table13Button->setGeometry(QRect(550, 690, 80, 25));
        Table13Button->setFont(font4);
        Table14Button = new QPushButton(centralwidget);
        Table14Button->setObjectName(QString::fromUtf8("Table14Button"));
        Table14Button->setGeometry(QRect(750, 690, 80, 25));
        Table14Button->setFont(font4);
        Table2Button = new QPushButton(centralwidget);
        Table2Button->setObjectName(QString::fromUtf8("Table2Button"));
        Table2Button->setGeometry(QRect(350, 290, 80, 25));
        Table2Button->setFont(font4);
        Table6Button = new QPushButton(centralwidget);
        Table6Button->setObjectName(QString::fromUtf8("Table6Button"));
        Table6Button->setGeometry(QRect(150, 490, 80, 25));
        Table6Button->setFont(font4);
        Table10Button = new QPushButton(centralwidget);
        Table10Button->setObjectName(QString::fromUtf8("Table10Button"));
        Table10Button->setGeometry(QRect(950, 490, 80, 25));
        Table10Button->setFont(font4);
        Table7Button = new QPushButton(centralwidget);
        Table7Button->setObjectName(QString::fromUtf8("Table7Button"));
        Table7Button->setGeometry(QRect(350, 490, 80, 25));
        Table7Button->setFont(font4);
        Table8Button = new QPushButton(centralwidget);
        Table8Button->setObjectName(QString::fromUtf8("Table8Button"));
        Table8Button->setGeometry(QRect(550, 490, 80, 25));
        Table8Button->setFont(font4);
        Table4Button = new QPushButton(centralwidget);
        Table4Button->setObjectName(QString::fromUtf8("Table4Button"));
        Table4Button->setGeometry(QRect(750, 290, 80, 25));
        Table4Button->setFont(font4);
        Table5Button = new QPushButton(centralwidget);
        Table5Button->setObjectName(QString::fromUtf8("Table5Button"));
        Table5Button->setGeometry(QRect(950, 290, 80, 25));
        Table5Button->setFont(font4);
        Table3Button = new QPushButton(centralwidget);
        Table3Button->setObjectName(QString::fromUtf8("Table3Button"));
        Table3Button->setGeometry(QRect(550, 290, 80, 25));
        Table3Button->setFont(font4);
        Table9Button = new QPushButton(centralwidget);
        Table9Button->setObjectName(QString::fromUtf8("Table9Button"));
        Table9Button->setGeometry(QRect(750, 490, 80, 25));
        Table9Button->setFont(font4);
        Table1Button = new QPushButton(centralwidget);
        Table1Button->setObjectName(QString::fromUtf8("Table1Button"));
        Table1Button->setGeometry(QRect(150, 290, 80, 25));
        Table1Button->setFont(font4);
        chefLabel1 = new QLabel(centralwidget);
        chefLabel1->setObjectName(QString::fromUtf8("chefLabel1"));
        chefLabel1->setGeometry(QRect(1280, 750, 201, 201));
        chefLabel1_2 = new QLabel(centralwidget);
        chefLabel1_2->setObjectName(QString::fromUtf8("chefLabel1_2"));
        chefLabel1_2->setGeometry(QRect(1290, 180, 171, 231));
        chefLabel1_3 = new QLabel(centralwidget);
        chefLabel1_3->setObjectName(QString::fromUtf8("chefLabel1_3"));
        chefLabel1_3->setGeometry(QRect(1280, 470, 171, 241));
        ChefDessertLabel = new QLabel(centralwidget);
        ChefDessertLabel->setObjectName(QString::fromUtf8("ChefDessertLabel"));
        ChefDessertLabel->setGeometry(QRect(1270, 715, 141, 21));
        ChefDessertLabel->setFont(font4);
        ChefMealLabel = new QLabel(centralwidget);
        ChefMealLabel->setObjectName(QString::fromUtf8("ChefMealLabel"));
        ChefMealLabel->setGeometry(QRect(1270, 440, 201, 21));
        ChefMealLabel->setFont(font2);
        ChefEntranceLabel = new QLabel(centralwidget);
        ChefEntranceLabel->setObjectName(QString::fromUtf8("ChefEntranceLabel"));
        ChefEntranceLabel->setGeometry(QRect(1280, 150, 201, 21));
        ChefEntranceLabel->setFont(font2);
        CookDessertButton = new QPushButton(centralwidget);
        CookDessertButton->setObjectName(QString::fromUtf8("CookDessertButton"));
        CookDessertButton->setGeometry(QRect(1140, 830, 111, 41));
        QFont font5;
        font5.setFamily(QString::fromUtf8("Monotype Corsiva"));
        font5.setPointSize(16);
        font5.setBold(false);
        font5.setWeight(50);
        CookDessertButton->setFont(font5);
        CookMealButton1 = new QPushButton(centralwidget);
        CookMealButton1->setObjectName(QString::fromUtf8("CookMealButton1"));
        CookMealButton1->setGeometry(QRect(1140, 620, 111, 41));
        CookMealButton1->setFont(font5);
        CookMealButton2 = new QPushButton(centralwidget);
        CookMealButton2->setObjectName(QString::fromUtf8("CookMealButton2"));
        CookMealButton2->setGeometry(QRect(1140, 570, 111, 41));
        CookMealButton2->setFont(font5);
        CookMealButton3 = new QPushButton(centralwidget);
        CookMealButton3->setObjectName(QString::fromUtf8("CookMealButton3"));
        CookMealButton3->setGeometry(QRect(1140, 520, 111, 41));
        CookMealButton3->setFont(font5);
        CookEntranceButton = new QPushButton(centralwidget);
        CookEntranceButton->setObjectName(QString::fromUtf8("CookEntranceButton"));
        CookEntranceButton->setGeometry(QRect(1140, 260, 111, 41));
        CookEntranceButton->setFont(font5);
        ChefTextField = new QTextEdit(centralwidget);
        ChefTextField->setObjectName(QString::fromUtf8("ChefTextField"));
        ChefTextField->setGeometry(QRect(1523, 70, 381, 141));
        ChefTextField->setFont(font1);
        ChefTextField->setReadOnly(true);
        ChefTextLabel = new QLabel(centralwidget);
        ChefTextLabel->setObjectName(QString::fromUtf8("ChefTextLabel"));
        ChefTextLabel->setGeometry(QRect(1540, 30, 91, 31));
        ChefTextLabel->setFont(font2);
        TableTime1 = new QLabel(centralwidget);
        TableTime1->setObjectName(QString::fromUtf8("TableTime1"));
        TableTime1->setGeometry(QRect(180, 250, 55, 41));
        TableTime1->setFont(font4);
        TableTime2 = new QLabel(centralwidget);
        TableTime2->setObjectName(QString::fromUtf8("TableTime2"));
        TableTime2->setGeometry(QRect(380, 250, 55, 41));
        TableTime2->setFont(font4);
        TableTime3 = new QLabel(centralwidget);
        TableTime3->setObjectName(QString::fromUtf8("TableTime3"));
        TableTime3->setGeometry(QRect(580, 250, 55, 41));
        TableTime3->setFont(font4);
        TableTime4 = new QLabel(centralwidget);
        TableTime4->setObjectName(QString::fromUtf8("TableTime4"));
        TableTime4->setGeometry(QRect(780, 250, 55, 41));
        TableTime4->setFont(font4);
        TableTime5 = new QLabel(centralwidget);
        TableTime5->setObjectName(QString::fromUtf8("TableTime5"));
        TableTime5->setGeometry(QRect(980, 250, 55, 41));
        TableTime5->setFont(font4);
        TableTime7 = new QLabel(centralwidget);
        TableTime7->setObjectName(QString::fromUtf8("TableTime7"));
        TableTime7->setGeometry(QRect(380, 450, 55, 41));
        TableTime7->setFont(font4);
        TableTime9 = new QLabel(centralwidget);
        TableTime9->setObjectName(QString::fromUtf8("TableTime9"));
        TableTime9->setGeometry(QRect(780, 450, 55, 41));
        TableTime9->setFont(font4);
        TableTime8 = new QLabel(centralwidget);
        TableTime8->setObjectName(QString::fromUtf8("TableTime8"));
        TableTime8->setGeometry(QRect(580, 450, 55, 41));
        TableTime8->setFont(font4);
        TableTime10 = new QLabel(centralwidget);
        TableTime10->setObjectName(QString::fromUtf8("TableTime10"));
        TableTime10->setGeometry(QRect(980, 450, 55, 41));
        TableTime10->setFont(font4);
        TableTime6 = new QLabel(centralwidget);
        TableTime6->setObjectName(QString::fromUtf8("TableTime6"));
        TableTime6->setGeometry(QRect(180, 450, 55, 41));
        TableTime6->setFont(font4);
        TableTime12 = new QLabel(centralwidget);
        TableTime12->setObjectName(QString::fromUtf8("TableTime12"));
        TableTime12->setGeometry(QRect(380, 650, 55, 41));
        TableTime12->setFont(font4);
        TableTime14 = new QLabel(centralwidget);
        TableTime14->setObjectName(QString::fromUtf8("TableTime14"));
        TableTime14->setGeometry(QRect(780, 650, 55, 41));
        TableTime14->setFont(font4);
        TableTime13 = new QLabel(centralwidget);
        TableTime13->setObjectName(QString::fromUtf8("TableTime13"));
        TableTime13->setGeometry(QRect(580, 650, 55, 41));
        TableTime13->setFont(font4);
        TableTime15 = new QLabel(centralwidget);
        TableTime15->setObjectName(QString::fromUtf8("TableTime15"));
        TableTime15->setGeometry(QRect(980, 650, 55, 41));
        TableTime15->setFont(font4);
        TableTime11 = new QLabel(centralwidget);
        TableTime11->setObjectName(QString::fromUtf8("TableTime11"));
        TableTime11->setGeometry(QRect(180, 650, 55, 41));
        TableTime11->setFont(font4);
        TableTime17 = new QLabel(centralwidget);
        TableTime17->setObjectName(QString::fromUtf8("TableTime17"));
        TableTime17->setGeometry(QRect(380, 850, 55, 41));
        TableTime17->setFont(font4);
        TableTime19 = new QLabel(centralwidget);
        TableTime19->setObjectName(QString::fromUtf8("TableTime19"));
        TableTime19->setGeometry(QRect(780, 850, 55, 41));
        TableTime19->setFont(font4);
        TableTime18 = new QLabel(centralwidget);
        TableTime18->setObjectName(QString::fromUtf8("TableTime18"));
        TableTime18->setGeometry(QRect(580, 850, 55, 41));
        TableTime18->setFont(font4);
        TableTime20 = new QLabel(centralwidget);
        TableTime20->setObjectName(QString::fromUtf8("TableTime20"));
        TableTime20->setGeometry(QRect(980, 850, 55, 41));
        TableTime20->setFont(font4);
        TableTime16 = new QLabel(centralwidget);
        TableTime16->setObjectName(QString::fromUtf8("TableTime16"));
        TableTime16->setGeometry(QRect(180, 850, 55, 41));
        TableTime16->setFont(font4);
        CashTextField = new QTextEdit(centralwidget);
        CashTextField->setObjectName(QString::fromUtf8("CashTextField"));
        CashTextField->setGeometry(QRect(140, 40, 361, 171));
        QFont font6;
        font6.setFamily(QString::fromUtf8("Arial Black"));
        font6.setItalic(false);
        CashTextField->setFont(font6);
        CashTextField->setReadOnly(true);
        WashTextField = new QTextEdit(centralwidget);
        WashTextField->setObjectName(QString::fromUtf8("WashTextField"));
        WashTextField->setGeometry(QRect(700, 40, 361, 171));
        WashTextField->setFont(font6);
        WashTextField->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        WashTextField->setReadOnly(true);
        CashPauseButton = new QPushButton(centralwidget);
        CashPauseButton->setObjectName(QString::fromUtf8("CashPauseButton"));
        CashPauseButton->setGeometry(QRect(600, 120, 81, 31));
        CashPauseButton->setFont(font5);
        TypeCashButton = new QPushButton(centralwidget);
        TypeCashButton->setObjectName(QString::fromUtf8("TypeCashButton"));
        TypeCashButton->setGeometry(QRect(40, 120, 81, 31));
        TypeCashButton->setFont(font5);
        CashierLabel = new QLabel(centralwidget);
        CashierLabel->setObjectName(QString::fromUtf8("CashierLabel"));
        CashierLabel->setGeometry(QRect(160, 10, 361, 20));
        CashierLabel->setFont(font4);
        CashierLabel_2 = new QLabel(centralwidget);
        CashierLabel_2->setObjectName(QString::fromUtf8("CashierLabel_2"));
        CashierLabel_2->setGeometry(QRect(710, 10, 361, 20));
        CashierLabel_2->setFont(font4);
        label = new QLabel(centralwidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(220, -10, 55, 61));
        label->setFont(font4);
        cantDePlatos = new QLabel(centralwidget);
        cantDePlatos->setObjectName(QString::fromUtf8("cantDePlatos"));
        cantDePlatos->setGeometry(QRect(830, -10, 55, 61));
        cantDePlatos->setFont(font4);
        SimuladorWindow->setCentralWidget(centralwidget);
        cantDePlatos->raise();
        label->raise();
        QueueTextField->raise();
        QueueLabel->raise();
        QueueSizeLabel->raise();
        ButtonClientGenerator->raise();
        ClientAssignerTextFiel->raise();
        AssignTablesButton->raise();
        AssignerLabel->raise();
        TableInfoTextFiedl->raise();
        TableLabel->raise();
        TableIDLabel->raise();
        Table16Button->raise();
        Table17Button->raise();
        Table18Button->raise();
        Table19Button->raise();
        Table20Button->raise();
        Table11Button->raise();
        Table15Button->raise();
        Table12Button->raise();
        Table13Button->raise();
        Table14Button->raise();
        Table2Button->raise();
        Table6Button->raise();
        Table10Button->raise();
        Table7Button->raise();
        Table8Button->raise();
        Table4Button->raise();
        Table5Button->raise();
        Table3Button->raise();
        Table9Button->raise();
        Table1Button->raise();
        chefLabel1->raise();
        chefLabel1_2->raise();
        chefLabel1_3->raise();
        ChefDessertLabel->raise();
        ChefMealLabel->raise();
        ChefEntranceLabel->raise();
        CookDessertButton->raise();
        CookMealButton1->raise();
        CookMealButton2->raise();
        CookMealButton3->raise();
        CookEntranceButton->raise();
        ChefTextField->raise();
        ChefTextLabel->raise();
        TableTime1->raise();
        TableTime2->raise();
        TableTime3->raise();
        TableTime4->raise();
        TableTime5->raise();
        TableTime7->raise();
        TableTime9->raise();
        TableTime8->raise();
        TableTime10->raise();
        TableTime6->raise();
        TableTime12->raise();
        TableTime14->raise();
        TableTime13->raise();
        TableTime15->raise();
        TableTime11->raise();
        TableTime17->raise();
        TableTime19->raise();
        TableTime18->raise();
        TableTime20->raise();
        TableTime16->raise();
        CashTextField->raise();
        WashTextField->raise();
        CashPauseButton->raise();
        TypeCashButton->raise();
        CashierLabel_2->raise();
        CashierLabel->raise();
        menubar = new QMenuBar(SimuladorWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1913, 25));
        menuMeseros = new QMenu(menubar);
        menuMeseros->setObjectName(QString::fromUtf8("menuMeseros"));
        menuTiempos = new QMenu(menubar);
        menuTiempos->setObjectName(QString::fromUtf8("menuTiempos"));
        menuReset = new QMenu(menubar);
        menuReset->setObjectName(QString::fromUtf8("menuReset"));
        menuMenu = new QMenu(menubar);
        menuMenu->setObjectName(QString::fromUtf8("menuMenu"));
        menuReservas = new QMenu(menubar);
        menuReservas->setObjectName(QString::fromUtf8("menuReservas"));
        menuSimulacion = new QMenu(menubar);
        menuSimulacion->setObjectName(QString::fromUtf8("menuSimulacion"));
        SimuladorWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(SimuladorWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        SimuladorWindow->setStatusBar(statusbar);

        menubar->addAction(menuMeseros->menuAction());
        menubar->addAction(menuTiempos->menuAction());
        menubar->addAction(menuReset->menuAction());
        menubar->addAction(menuMenu->menuAction());
        menubar->addAction(menuReservas->menuAction());
        menubar->addAction(menuSimulacion->menuAction());
        menuMeseros->addSeparator();
        menuMeseros->addAction(actionMesero_1);
        menuMeseros->addAction(actionMesero_2);
        menuMeseros->addAction(actionMesero_3);
        menuMeseros->addAction(actionMesero_4);
        menuMeseros->addAction(actionMesero_5);
        menuMeseros->addAction(actionMesero_6);
        menuMeseros->addAction(actionMesero_7);
        menuMeseros->addAction(actionMesero_8);
        menuMeseros->addAction(actionMesero_9);
        menuMeseros->addAction(actionMesero_10);
        menuMeseros->addAction(actionMesero_11);
        menuMeseros->addAction(actionMesero_12);
        menuMeseros->addAction(actionMesero_13);
        menuMeseros->addAction(actionMesero_14);
        menuMeseros->addAction(actionMesero_15);
        menuMeseros->addAction(actionMesero_16);
        menuMeseros->addAction(actionMesero_17);
        menuMeseros->addAction(actionMesero_18);
        menuMeseros->addAction(actionMesero_19);
        menuMeseros->addAction(actionMesero_20);
        menuTiempos->addAction(actionIntervalo_de_llegada);
        menuTiempos->addAction(actionProbabilidad_de_plato_fuerte);
        menuReset->addAction(actionRestart_Simulation);
        menuMenu->addAction(actionVer_Menu);
        menuReservas->addAction(actionSolicitar_Reserva);
        menuSimulacion->addAction(actionStart);
        menuSimulacion->addAction(actionDetener);

        retranslateUi(SimuladorWindow);

        QMetaObject::connectSlotsByName(SimuladorWindow);
    } // setupUi

    void retranslateUi(QMainWindow *SimuladorWindow)
    {
        SimuladorWindow->setWindowTitle(QCoreApplication::translate("SimuladorWindow", "SimuladorWindow", nullptr));
        actionMesero_1->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 1", nullptr));
        actionMesero_2->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 2", nullptr));
        actionMesero_3->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 3", nullptr));
        actionMesero_4->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 4", nullptr));
        actionMesero_5->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 5", nullptr));
        actionMesero_6->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 6", nullptr));
        actionMesero_7->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 7 ", nullptr));
        actionMesero_8->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 8", nullptr));
        actionMesero_9->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 9", nullptr));
        actionMesero_10->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 10", nullptr));
        actionMesero_11->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 11", nullptr));
        actionMesero_12->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 12", nullptr));
        actionMesero_13->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 13", nullptr));
        actionMesero_14->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 14", nullptr));
        actionMesero_15->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 15", nullptr));
        actionMesero_16->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 16", nullptr));
        actionMesero_17->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 17", nullptr));
        actionMesero_18->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 18", nullptr));
        actionMesero_19->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 19", nullptr));
        actionMesero_20->setText(QCoreApplication::translate("SimuladorWindow", "Mesero 20", nullptr));
        actionIntervalo_de_llegada->setText(QCoreApplication::translate("SimuladorWindow", "Intervalo de llegada", nullptr));
        actionProbabilidad_de_plato_fuerte->setText(QCoreApplication::translate("SimuladorWindow", "Probabilidad de platillos", nullptr));
        actionRestart_Simulation->setText(QCoreApplication::translate("SimuladorWindow", "Reiniciar Simulacion", nullptr));
        actionVer_Menu->setText(QCoreApplication::translate("SimuladorWindow", "Ver Menu", nullptr));
        actionSolicitar_Reserva->setText(QCoreApplication::translate("SimuladorWindow", "Solicitar Reserva", nullptr));
        actionStart->setText(QCoreApplication::translate("SimuladorWindow", "Iniciar", nullptr));
        actionDetener->setText(QCoreApplication::translate("SimuladorWindow", "Detener", nullptr));
        QueueLabel->setText(QCoreApplication::translate("SimuladorWindow", "Gente en cola: ", nullptr));
        QueueSizeLabel->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        ButtonClientGenerator->setText(QCoreApplication::translate("SimuladorWindow", "Generar Clientes", nullptr));
        AssignTablesButton->setText(QCoreApplication::translate("SimuladorWindow", "Asignar Cientes", nullptr));
        AssignerLabel->setText(QCoreApplication::translate("SimuladorWindow", "Recepcionista", nullptr));
        TableLabel->setText(QCoreApplication::translate("SimuladorWindow", "Mesa #", nullptr));
        TableIDLabel->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        Table16Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table17Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table18Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table19Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table20Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table11Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table15Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table12Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table13Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table14Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table2Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table6Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table10Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table7Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table8Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table4Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table5Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table3Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table9Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        Table1Button->setText(QCoreApplication::translate("SimuladorWindow", "info", nullptr));
        chefLabel1->setText(QString());
        chefLabel1_2->setText(QString());
        chefLabel1_3->setText(QString());
        ChefDessertLabel->setText(QCoreApplication::translate("SimuladorWindow", "Chef Postres", nullptr));
        ChefMealLabel->setText(QCoreApplication::translate("SimuladorWindow", "Chefs Platos Fuertes", nullptr));
        ChefEntranceLabel->setText(QCoreApplication::translate("SimuladorWindow", "Chef Entradas", nullptr));
        CookDessertButton->setText(QCoreApplication::translate("SimuladorWindow", "Cocinar", nullptr));
        CookMealButton1->setText(QCoreApplication::translate("SimuladorWindow", "Cocinar", nullptr));
        CookMealButton2->setText(QCoreApplication::translate("SimuladorWindow", "Cocinar", nullptr));
        CookMealButton3->setText(QCoreApplication::translate("SimuladorWindow", "Cocinar", nullptr));
        CookEntranceButton->setText(QCoreApplication::translate("SimuladorWindow", "Cocinar", nullptr));
        ChefTextLabel->setText(QCoreApplication::translate("SimuladorWindow", "Chefs:", nullptr));
        TableTime1->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        TableTime2->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        TableTime3->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        TableTime4->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        TableTime5->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        TableTime7->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        TableTime9->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        TableTime8->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        TableTime10->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        TableTime6->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        TableTime12->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        TableTime14->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        TableTime13->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        TableTime15->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        TableTime11->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        TableTime17->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        TableTime19->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        TableTime18->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        TableTime20->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        TableTime16->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        CashPauseButton->setText(QCoreApplication::translate("SimuladorWindow", "Lavar", nullptr));
        TypeCashButton->setText(QCoreApplication::translate("SimuladorWindow", "Cola", nullptr));
        CashierLabel->setText(QCoreApplication::translate("SimuladorWindow", "Caja:", nullptr));
        CashierLabel_2->setText(QCoreApplication::translate("SimuladorWindow", "Lavaplatos:", nullptr));
        label->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        cantDePlatos->setText(QCoreApplication::translate("SimuladorWindow", "0", nullptr));
        menuMeseros->setTitle(QCoreApplication::translate("SimuladorWindow", "Meseros", nullptr));
        menuTiempos->setTitle(QCoreApplication::translate("SimuladorWindow", "Configuracion", nullptr));
        menuReset->setTitle(QCoreApplication::translate("SimuladorWindow", "Reset", nullptr));
        menuMenu->setTitle(QCoreApplication::translate("SimuladorWindow", "Menu", nullptr));
        menuReservas->setTitle(QCoreApplication::translate("SimuladorWindow", "Reservas", nullptr));
        menuSimulacion->setTitle(QCoreApplication::translate("SimuladorWindow", "Simulacion", nullptr));
    } // retranslateUi

};

namespace Ui {
    class SimuladorWindow: public Ui_SimuladorWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SIMULADORWINDOW_H
